/**
 * \file 
 *
 * \brief A dynamic Lexical Scanner
 *
 * A dynamic lexical scanner that can be embedded into a runtime. Performing
 * lexical analysis at runtime allows the caller to determine (at runtime)
 * the rules for reading tokens.
 *
 * This differs from tools such as flex in that the actual rules for
 * recognising lexems are determined at runtime. With other lexical scanners
 * the rules for parsing input into lexemes are specified at compile-time
 * and thus the rules cannot be changed as the program runs. Xlib's lexical
 * scanner (xlex) is primarily for creating lexeme-recognising rules at
 * runtime.
 *
 * As such, xlex performs a lot slower at recognising input than the code
 * generated by tools such as flex.
 *
 * The scanner is used by simply creating a context using \a xlex_new(),
 * adding rules to this context using \a xlex_add() and finally executing
 * the scanner with some input using \a xlex_exec().
 *
 * Pattern matching is performed using regular expressions in a "greedy"
 * manner, meaning that as much of the input as possible would be matched 
 * to a regular expression.
 *
 * \sa xlex_new(), xlex_add(), xlex_exec(), xlex_del()
 *
 * xlex is part of the libxc (Extended C Library) and falls
 * under the relevant copyright license in libxc.
 *
 * \author Lelanthran Krishna Manickum
 *
 */


#include <stdio.h>
#include <string.h>

#include <regex.h>

#include "xdict/xdict.h"
#include "xstring/xstring.h"
#include "xvector/xvector.h"

#include "xlex/xlex.h"

#define MAX_LINE_LENGTH      (4096 * 2)

struct record_t {
   regex_t re;
   int errnum;
   char *errmsg;
   void (*fptr) (char *, size_t, size_t);
   size_t scratch;
   size_t rm_so, rm_eo;
};

typedef struct record_t record_t;

static void rec_del (record_t *rec)
{
   if (rec) {
      regfree (&rec->re);
      if (rec->errmsg) free (rec->errmsg);
      free (rec);
   }
}

static record_t *rec_new (char *re, void (*fptr) (char *, size_t, size_t))
{
   char *errmsg;
   record_t *ret = malloc (sizeof *ret);
   if (!ret) return NULL;
   ret->errnum = regcomp (&ret->re, re, REG_EXTENDED);
   errmsg = malloc (sizeof *errmsg * MAX_LINE_LENGTH);
   if (!errmsg) {
      rec_del (ret);
      return NULL;
   }
   if (ret->errnum!=0) {
      regerror (ret->errnum, &ret->re, errmsg, sizeof errmsg);
   } else {
      strcpy (errmsg, "No error");
   }
   ret->errmsg = xstr_dup (errmsg);
   ret->fptr = fptr;
   free (errmsg);
   return ret;
}

struct xlex_t {
   char *name;
   xvector_t *records;
};


/**
 * \brief Create a new lexical scanner
 *
 * Create a new lexical scanner for use by the caller with an optional name. 
 * The return value must be used in all the xlex function calls.
 *
 * \sa xlex_del(), xlex_add(), xlex_exec()
 *
 * @param[in] name Optional name of the scanner to be created. This has
 * no effect other than to give the scanner a name. Can be left NULL.
 *
 * @return On success a handle of type \a xlex_t * is returned which the
 * caller must free with \a xlex_del(). On failure NULL is returned.
 * 
 * \a Example:
 *
 * \verbatim
   void found_string (char *matchg, size_t line, size_t offset)
   {
      printf ("Found a string %zu:%zu- '%s'\n", line, offset, match);
   }

   int main (void)
   {
      size_t line_num = 1;
      // Create a new lexical scanner
      xlex_t *ls = xlex_new ("find-strings");

      // Add the pattern we wish to scan for
      xlex_add (ls, "\".*\"", found_string);

      // Execute the scanner on our input
      while (!feof (stdin) && !ferror (stdin)) {
         static char input[4096];
         if (!fgets (input, sizeof input -1, stdin)) break;
         xlex_exec (ls, input, line_num++);
      }

      xlex_del (ls);
      return EXIT_SUCCESS;
   }
  \endverbatim
 */
xlex_t *xlex_new (char *name)
{
   xlex_t *ret = malloc (sizeof *ret);
   if (!ret) return NULL;
   ret->records = NULL;
   ret->name = xstr_dup (name);
   if (!ret->name) {
      xlex_del (ret);
      return NULL;
   } 
   return ret;
}

/**
 * \brief Add a rule to the lexical scanner
 *
 * Adds a new rule in the form of a regular expression to the lexical scanner.
 * The rule is composed of both a regular expression and a pointer to a 
 * function. Whenever the scanner matches the given regular expression in the
 * input it will execute the corresponding function with the text found,
 * the line number that the lexical scanner was passed and the character 
 * position in which the match was made.
 *
 * The scanner matches "greedily" in that as much of the input text as possible
 * will be matched to a regular expression. Once a match is made the 
 * corresponding function is executed with the matched text, the line number
 * and the character position on that line. The function prototype for the
 * caller-supplied function is as follows:
 *
 * void func_name (char *match, size_t line, size_t offset);
 *
 * \sa xlex_del(), xlex_new(), xlex_exec()
 *
 * @param[in] xl The scanner that was created with \a xlex_new().
 * @param[in] re The regular expression that will be used to execute this rule.
 * @param[in] fptr The function that will be executed on the matched text when
 *    this rule is matched with the regular expression \a re above. This 
 *    function returns nothing and receives four arguments: the matched text,
 *    the line number, character position and an extra argument supplied
 *    by the caller of \a xlex. The extra argument can be used to invoke
 *    \a xlex in a thread-safe manner by using the extra argument to identify
 *    to the callback function \a fptr which instance of data it may update.
 *
 * @return On success the number of rules in the scanner is returned. On 
 * failure (size_t)-1 is returned.
 * 
 * \a Example:
 *
 * \verbatim
   void found_string (char *matchg, size_t line, size_t offset, void *ea)
   {
      printf ("Found a string %zu:%zu- '%s'\n", line, offset, match);
   }

   int main (void)
   {
      size_t line_num = 1;
      // Create a new lexical scanner
      xlex_t *ls = xlex_new ("find-strings");

      // Add the pattern we wish to scan for
      xlex_add (ls, "\".*\"", found_string);

      // Execute the scanner on our input
      while (!feof (stdin) && !ferror (stdin)) {
         static char input[4096];
         if (!fgets (input, sizeof input -1, stdin)) break;
         xlex_exec (ls, input, line_num++, NULL);
      }

      xlex_del (ls);
      return EXIT_SUCCESS;
   }
  \endverbatim
 */
size_t xlex_add (xlex_t *xl, char *re,
                 void (*fptr) (char *, void *, size_t, size_t))
{
   record_t *rec = rec_new (re, fptr);
   if (!rec) return (size_t)-1;
   xvector_t *tmp = xvector_ins_tail (xl->records, rec);
   if (!tmp) {
      rec_del (rec);
      return (size_t)-1;
   }
   xl->records = tmp;
   return XVECT_LENGTH (tmp);
}

static const char *xlex_iexec (xlex_t *xl, const char *input,
                               void *extra_data,
                               size_t line_num, size_t os)
{
   regmatch_t match_token;
   const char *tmp = input;
   size_t earliest = (size_t)-1; // Earliest match found
   size_t longest = 0;           // Longest of all the early matches found
   size_t match = (size_t)-1;    // The actual match (if found)

   for (size_t i=0; i<XVECT_LENGTH (xl->records); i++) {
      record_t *rec = XVECT_INDEX (xl->records, i);
      int retcode = regexec (&rec->re, tmp, 1, &match_token, 0);
      if (retcode!=0) {
         rec->scratch = 0;
         rec->rm_so = 0;
         rec->rm_eo = 0;
         continue;
      }
      rec->scratch = match_token.rm_eo - match_token.rm_so;
      rec->rm_so = match_token.rm_so;
      rec->rm_eo = match_token.rm_eo;
      // If this is the earliest match we've found, record it
      if (rec->rm_so <= earliest) {
         earliest = rec->rm_so;
      }
   }
   for (size_t i=0; i<XVECT_LENGTH (xl->records); i++) {
      record_t *rec = XVECT_INDEX (xl->records, i);
      if (rec->rm_so > earliest) continue;
      if (rec->scratch > longest) {
         longest = rec->scratch;
         match = i;
      }
   }
   if (match==(size_t)-1) {
      return NULL;
   }
   char *line = malloc (longest + 1);
   if (!line) {
      return NULL;
   }
   memset (line, 0, longest + 1);
   record_t *rec = XVECT_INDEX (xl->records, match);
   memcpy (line, &tmp[rec->rm_so], rec->rm_eo - rec->rm_so);
   rec->fptr (line, line_num, rec->rm_so + os);
   free (line);
   return &tmp[rec->rm_eo];
}

/**
 * \brief Execute the scanner on text
 *
 * Execute the scanner on the given input text and call the corresponding
 * function when a match is made. See the example below for more details.
 *
 * \sa xlex_del(), xlex_new(), xlex_add()
 *
 * @param[in] xl The scanner that was created with \a xlex_new().
 * @param[in] input The input text to be scanned.
 * @param[in] line_num The current line number supplied by the caller.
 * @param[in] extra_arg Additional arguments to be supplied to the callback
 *          function that gets invoked for each match.
 *
 * @return On success 0 is returned. On failure (size_t)-1 is returned.
 * 
 * \a Example:
 *
 * \verbatim
   void found_string (char *matchg, size_t line, size_t offset, void *ea)
   {
      printf ("Found a string %zu:%zu- '%s'\n", line, offset, match);
   }

   int main (void)
   {
      size_t line_num = 1;
      // Create a new lexical scanner
      xlex_t *ls = xlex_new ("find-strings");

      // Add the pattern we wish to scan for
      xlex_add (ls, "\".*\"", found_string);

      // Execute the scanner on our input
      while (!feof (stdin) && !ferror (stdin)) {
         static char input[4096];
         if (!fgets (input, sizeof input -1, stdin)) break;
         xlex_exec (ls, input, line_num++, NULL);
      }

      xlex_del (ls);
      return EXIT_SUCCESS;
   }
  \endverbatim
 */
int xlex_exec (xlex_t *xl, const char *line, size_t line_num, void *extra_arg)
{
   const char *tmp = line;
   while (tmp && *tmp) {
      tmp = xlex_iexec (xl, tmp, extra_arg, line_num, tmp - line);
   }
   return 0;
}

/**
 * \brief Delete and free all resources associated with a scanner
 *
 * Deletes a context specified by \a xl and frees all resources
 * associated with that context. The context \a xl must have been
 * created with a call to \a xlex_new().
 *
 * \sa xlex_exec(), xlex_new(), xlex_add()
 *
 * @param[in] xl The scanner that was created with \a xlex_new().

 * \a Example:
 *
 * \verbatim
   void found_string (char *matchg, size_t line, size_t offset)
   {
      printf ("Found a string %zu:%zu- '%s'\n", line, offset, match);
   }

   int main (void)
   {
      size_t line_num = 1;
      // Create a new lexical scanner
      xlex_t *ls = xlex_new ("find-strings");

      // Add the pattern we wish to scan for
      xlex_add (ls, "\".*\"", found_string);

      // Execute the scanner on our input
      while (!feof (stdin) && !ferror (stdin)) {
         static char input[4096];
         if (!fgets (input, sizeof input -1, stdin)) break;
         xlex_exec (ls, input, line_num++);
      }
      
      // Finally delete the scanner and free all the resources
      xlex_del (ls);
      return EXIT_SUCCESS;
   }
  \endverbatim
 */
void xlex_del (xlex_t *xl)
{
   if (xl) {
      if (xl->name) free (xl->name);
      if (xl->records) {
         xvector_iterate (xl->records, (void (*)( void *))rec_del);
         xvector_free (xl->records);
      }
      free (xl);
   }
}


