[package]
name = "ainux_kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
volatile = "0.6.1"
spin = "0.9.8" # Spinlocks for synchronization
linked_list_allocator = "0.10.5"
lazy_static = { version = "1.4", features = ["spin_no_std"] }

[build-dependencies]
cc = "1.0"
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
