timeout: 0
serial: yes
verbose: yes
interface_branding: Ainux BOOT

/Ainux
    protocol: limine
    # KASLR for security, though can be disabled for debugging
    kernel_path: boot():/boot/ainux_kernel
