use crate::lexer::{Lexer, Token, Span};
use std::vec::Vec;
use std::collections::HashMap;

use std::fmt;



#[derive(Debug)]
pub struct CompileError {
    pub message: String,
    pub span: Span,
}

impl fmt::Display for CompileError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{} (Line {}, Col {})", self.message, self.span.line, self.span.col)
    }
}

impl CompileError {
    fn new(msg: String, span: Span) -> Self {
        Self { message: msg, span }
    }
}

#[derive(Debug)]
pub struct CompileResult {
    pub output: Option<String>,
    pub errors: Vec<CompileError>,
}

pub fn compile_to_asm_source(source: &str) -> Result<String, Vec<CompileError>> {
    let mut parser = Parser::new(source);
    match parser.parse_to_asm() {
        Ok(out) => {
            if parser.errors.is_empty() {
                Ok(out)
            } else {
                Err(parser.errors)
            }
        },
        Err(e) => {
           // Critical failure (e.g. unhandled), but we also have accumulated errors.
           parser.errors.push(e);
           Err(parser.errors)
        }
    }
}

pub fn compile_high_level(source: &str) -> Result<Vec<u8>, Vec<CompileError>> {
    match compile_to_asm_source(source) {
        Ok(asm) => {
            crate::compiler::compile(&asm).map_err(|e| vec![CompileError::new(e, Span { line: 0, col: 0 })])
        },
        Err(e) => Err(e),
    }
}

struct Parser {
    lexer: Lexer,
    label_id_counter: usize,
    var_map: HashMap<String, u64>,
    var_addr_counter: u64,
    current_token: Token,
    current_span: Span,
    prev_span: Span,
    asm_output: String,
    errors: Vec<CompileError>,
}

impl Parser {
    fn new(source: &str) -> Self {
        let mut l = Lexer::new(source);
        let (first, span) = l.next_token();
        Self {
            lexer: l,
            label_id_counter: 0,
            var_map: HashMap::new(),
            var_addr_counter: 0,
            current_token: first,
            current_span: span,
            prev_span: span,
            asm_output: String::new(),
            errors: Vec::new(),
        }
    }

    fn advance(&mut self) {
        self.prev_span = self.current_span;
        let (tok, span) = self.lexer.next_token();
        // println!("DEBUG: Advance. PrevTok: {:?} @ L{} C{}, NewTok: {:?} @ L{} C{}", 
        //    self.current_token, self.prev_span.line, self.prev_span.col, 
        //    tok, span.line, span.col);
        self.current_token = tok;
        self.current_span = span;
    }

    fn emit(&mut self, s: &str) {
        self.asm_output.push_str(s);
        self.asm_output.push('\n');
    }

    // Recover from error by skipping up to semicolon or end of block
    fn synchronize(&mut self) {
        // self.advance(); // Don't advance immediately, check if current is sync point
        while self.current_token != Token::EOF {
             if self.current_token == Token::SemiColon {
                 self.advance();
                 return;
             }
             match self.current_token {
                 Token::Class | Token::Func | Token::Var | Token::For | 
                 Token::If | Token::While | Token::Print | Token::Return => return, // Start of new statement
                 Token::RBrace => return, // End of block
                 _ => self.advance(),
             }
        }
    }
    
    // Non-fatal error logging
    fn error_at_current(&mut self, msg: String) {
        self.errors.push(CompileError::new(msg, self.current_span));
    }

    fn parse_to_asm(&mut self) -> Result<String, CompileError> {
        self.emit("; Auto-Generated by Nux High-Level Compiler");
        self.emit("JMP __start_execution"); 
        
        let mut main_body = String::new();
        let mut definitions = String::new();
        
        loop {
            match &self.current_token {
                Token::EOF => break,
                Token::Class => {
                     if let Err(e) = self.parse_class(&mut definitions) {
                          self.errors.push(e);
                          self.synchronize();
                     }
                },
                Token::Func => {
                     if let Err(e) = self.parse_func(&mut definitions, "") {
                         self.errors.push(e);
                         self.synchronize();
                     }
                },
                Token::Identifier(_) | Token::Print | Token::Println | Token::Input |
                Token::If | Token::While | Token::For | Token::Asm => {
                    if let Err(e) = self.parse_statement_or_expr(&mut main_body) {
                        self.errors.push(e);
                        self.synchronize();
                    }
                },
                Token::SemiColon => self.advance(), // Empty
                Token::LBrace => {
                     if let Err(e) = self.parse_block(&mut main_body) {
                         self.errors.push(e);
                         self.synchronize();
                     }
                },
                _ => {
                    self.error_at_current(format!("Unexpected token at top level: {:?}", self.current_token));
                    self.advance();
                }
            }
        }
        
        // Append Main Body
        self.emit("__start_execution:");
        self.asm_output.push_str(&main_body);
        
        // Final JMP loop or exit?
        self.emit("EXIT");
        
        Ok(self.asm_output.clone())
    }

    // --- Parsing Routines ---

    fn error<T>(&self, msg: String) -> Result<T, CompileError> {
        Err(CompileError::new(msg, self.current_span))
    }

    fn parse_class(&mut self, out: &mut String) -> Result<(), CompileError> {
        self.advance(); // consume 'class'
        let name = match &self.current_token {
            Token::Identifier(s) => s.clone(),
            _ => return self.error("Expected class name".to_string()),
        };
        self.advance();
        
        if self.current_token != Token::LBrace { return self.error("Expected '{' after class name".to_string()); }
        self.advance();
        
        // Inside class, we expect functions (methods).
        while self.current_token != Token::RBrace && self.current_token != Token::EOF {
            if self.current_token == Token::Func {
                self.parse_func(out, &name)?;
            } else {
                return self.error("Only functions allowed in classes for now".to_string());
            }
        }
        
        if self.current_token != Token::RBrace { return self.error("Expected '}'".to_string()); }
        self.advance();
        Ok(())
    }

    fn parse_func(&mut self, out: &mut String, class_prefix: &str) -> Result<(), CompileError> {
        self.advance(); // consume 'func'
        let name = match &self.current_token {
            Token::Identifier(s) => s.clone(),
            _ => return self.error("Expected function name".to_string()),
        };
        self.advance();
        
        if self.current_token != Token::LParen { return self.error("Expected '('".to_string()); }
        self.advance();
        // Args? Check RParen
        if self.current_token != Token::RParen { return self.error("Arguments not supported yet".to_string()); }
        self.advance();

        if self.current_token != Token::LBrace { return self.error("Expected '{'".to_string()); }
        
        // Generate Label
        let full_name = if class_prefix.is_empty() {
             name.clone()
        } else {
             format!("{}_{}", class_prefix, name)
        };
        
        out.push_str(&format!("; Function {}\n", full_name));
        out.push_str(&format!("JMP skip_{}\n", full_name)); // Skip definition
        out.push_str(&format!("{}:\n", full_name));
        
        // Parse Body
        let mut body_asm = String::new();
        self.parse_block(&mut body_asm)?;
        
        out.push_str(&body_asm);
        out.push_str("RET\n");
        out.push_str(&format!("skip_{}:\n", full_name));
        
        Ok(())
    }
    
    fn parse_block(&mut self, out: &mut String) -> Result<(), CompileError> {
        if self.current_token != Token::LBrace { return self.error("Expected block '{'".to_string()); }
        self.advance();
        
        while self.current_token != Token::RBrace && self.current_token != Token::EOF {
             if let Err(e) = self.parse_statement_or_expr(out) {
                 self.errors.push(e);
                 self.synchronize();
             }
        }
        
        if self.current_token != Token::RBrace { return self.error("Expected '}'".to_string()); }
        self.advance();
        Ok(())
    }

    fn parse_statement_or_expr(&mut self, out: &mut String) -> Result<(), CompileError> {
        match &self.current_token {
             Token::Print => {
                 self.advance();
                 self.parse_print(out, false)?;
             },
             Token::Println => {
                 self.advance();
                 self.parse_print(out, true)?;
             },
             Token::Identifier(name) => {
                 // Could be "func()" or "obj.method()" or "MyClass.method()"
                 // For now, simpler: identifier(...) -> CALL identifier
                 // Or identifier.identifier(...) -> CALL identifier_identifier
                 let part1 = name.clone();
                 self.advance(); // skip name
                 
                 // println!("DEBUG: Ident={}, Next={:?}", part1, self.current_token);

                 if self.current_token == Token::Dot {
                     println!("DEBUG: Branch Dot");
                     // ...
                 } else if self.current_token == Token::LParen {
                     println!("DEBUG: Branch Call");
                     // ...
                 } else if {
                     let is_ident = matches!(self.current_token, Token::Identifier(_));
                     // println!("DEBUG: Checking Var Decl. IsIdent={}, Part1='{}'", is_ident, part1);
                     is_ident && part1 == "var" 
                 } {
                     // println!("DEBUG: Taking Var Decl Branch");
                      // var name = expr;
                      // Get name
                      let name = match &self.current_token {
                          Token::Identifier(s) => s.clone(),
                          _ => return self.error("Expected variable name".to_string()),
                      };
                      self.advance();
                      
                      if self.current_token != Token::Eq { return self.error("Expected =".to_string()); }
                      self.advance();
                      
                      // Parse Expr
                      self.parse_expression(out)?;
                      
                      self.parse_expression(out)?;
                      
                      if self.current_token != Token::SemiColon { 
                          self.errors.push(CompileError::new("Expected ;".to_string(), self.prev_span));
                          self.synchronize();
                          return Ok(());
                      }
                      self.advance();
                      
                      // Allocate and Store
                      if !self.var_map.contains_key(&name) {
                          self.var_map.insert(name.clone(), self.var_addr_counter);
                          self.var_addr_counter += 8; // i64 is 8 bytes
                      }
                      let addr = self.var_map[&name];
                      
                      // Store: Expr is on stack.
                      out.push_str(&format!("PUSH {}\nPOKE\n", addr));

                 } else if self.current_token == Token::Eq {
                      // Assignment: x = expr;
                      // part1 is 'x' (or name)
                       self.advance(); // Skip =
                       self.parse_expression(out)?;
                       
                       if self.current_token != Token::SemiColon { 
                            self.errors.push(CompileError::new("Expected ;".to_string(), self.prev_span));
                            self.synchronize();
                            return Ok(());
                       }
                       self.advance();
                       
                       if let Some(addr) = self.var_map.get(&part1) {
                           // println!("DEBUG: Assigning to variable '{}' at addr {}", part1, addr);
                           out.push_str(&format!("PUSH {}\nPOKE\n", addr));
                       } else {
                           // println!("DEBUG: Variable map keys: {:?}", self.var_map.keys());
                           return self.error(format!("Undefined variable for assignment: {}", part1));
                       }
                 } else {
                     return self.error(format!("Unexpected token after identifier {}", part1));
                 }
             },
             Token::Input => {
                // input(); statement
                self.advance();
                if self.current_token != Token::LParen { return self.error("Expected (".to_string()); }
                self.advance();
                if self.current_token != Token::RParen { return self.error("Expected )".to_string()); }
                self.advance();
                if self.current_token != Token::SemiColon { 
            println!("DEBUG: Pushing error (non-empty). PrevSpan L{} C{}", self.prev_span.line, self.prev_span.col);
            self.errors.push(CompileError::new("Expected ;".to_string(), self.prev_span));
            self.synchronize();
            return Ok(());
        }
                self.advance();
                out.push_str("INPUT\n");
             },
             Token::Return => {
                 self.advance();
                 if self.current_token != Token::SemiColon { return self.error("Return values not supported".to_string()); }
                 self.advance();
                 out.push_str("RET\n");
             },
             Token::If => {
                 // if (expr) { block } else { block }
                 self.advance(); // skip if
                 if self.current_token != Token::LParen { return self.error("Expected (".to_string()); }
                 self.advance();
                 
                 self.parse_expression(out)?;
                 
                 if self.current_token != Token::RParen { return self.error("Expected )".to_string()); }
                 self.advance();
                 
                 let label_id = self.label_id_counter;
                 self.label_id_counter += 1;
                 let label_else = format!("__if_else_{}", label_id);
                 let label_end = format!("__if_end_{}", label_id);
                 
                 // Expr is on stack (1 or 0). 
                 // Compare with 0. If 0 (False), Jump to Else/End.
                 out.push_str("PUSH 0\n");
                 out.push_str(&format!("JE {}\n", label_else));
                 
                 // True Block
                 self.parse_block(out)?;
                 out.push_str(&format!("JMP {}\n", label_end));
                 
                 out.push_str(&format!("{}:\n", label_else));
                 
                 // Else?
                 if self.current_token == Token::Else {
                     self.advance();
                     self.parse_block(out)?;
                 }
                 
                 out.push_str(&format!("{}:\n", label_end));
             },
             Token::While => {
                 // while (expr) { block }
                 self.advance();
                 if self.current_token != Token::LParen { return self.error("Expected (".to_string()); }
                 self.advance();
                 
                 let label_id = self.label_id_counter;
                 self.label_id_counter += 1;
                 let label_start = format!("__while_start_{}", label_id);
                 let label_end = format!("__while_end_{}", label_id);
                 
                 out.push_str(&format!("{}:\n", label_start));
                 
                 self.parse_expression(out)?;
                 
                 if self.current_token != Token::RParen { return self.error("Expected )".to_string()); }
                 self.advance();
                 
                 // Check False
                 out.push_str("PUSH 0\n");
                 out.push_str(&format!("JE {}\n", label_end));
                 
                 self.parse_block(out)?;
                 
                 out.push_str(&format!("JMP {}\n", label_start));
                 out.push_str(&format!("{}:\n", label_end));
             },
             Token::For => {
                 // for (init; cond; step) { block }
                 self.advance();
                 if self.current_token != Token::LParen { return self.error("Expected (".to_string()); }
                 self.advance();
                 
                 // Init
                 self.parse_statement_or_expr(out)?;
                 // Statement usually consumes semi-colon.
                 
                 let label_id = self.label_id_counter;
                 self.label_id_counter += 1;
                 let label_start = format!("__for_start_{}", label_id);
                 let label_step = format!("__for_step_{}", label_id);
                 let label_body = format!("__for_body_{}", label_id);
                 let label_end = format!("__for_end_{}", label_id);
                 
                 out.push_str(&format!("{}:\n", label_start));
                 
                 // Cond
                 self.parse_expression(out)?;
                 if self.current_token != Token::SemiColon { return self.error("Expected ; after condition".to_string()); }
                 self.advance();
                 
                 // Check Cond
                 out.push_str("PUSH 0\n");
                 out.push_str(&format!("JE {}\n", label_end));
                 out.push_str(&format!("JMP {}\n", label_body));
                 
                 // Step Section
                 out.push_str(&format!("{}:\n", label_step));
                 // Step is usually "i = i + 1" (expression/assignment)
                 // But parse_statement_or_expr expects trailing semicolon.
                 // In `for(..; ..; i=i+1)`, there is NO semicolon after step.
                 // This is tricky if our parser demands it.
                 // Hack: Parse expression (assignment is mostly expr logic if we supported it).
                 // My assignment logic is in `parse_statement`.
                 // I will support simple assignment here manually or refactor assignment to be an expression?
                 // Current assignment: `ident` ... `eq` ... `expr` ... `semi`.
                 // Let's call `parse_statement_or_expr` and hope for the best? No, it eats semicolon.
                 // Let's implement a "parse_assignment_no_semi" or just reuse parse_statement and allow NO semi?
                 
                 // Simpler: Just allow simple expression execution. Use assignment syntax but handle semicolon manually.
                 // Actually, let's just use `parse_statement_or_expr` and expect the user to PUT a semicolon?
                 // `for (var i=0; i<10; i=i+1;)`. Weird but consistent.
                 // OR I peek and temporarily insert a semicolon token?
                 // Let's just try to parse assignment logic manually here.
                 
                 match &self.current_token {
                     Token::Identifier(name) => {
                         let part1 = name.clone();
                         self.advance();
                         if self.current_token == Token::Eq {
                            self.advance();
                            self.parse_expression(out)?;
                            
                            // Assignment Store logic
                            if let Some(addr) = self.var_map.get(&part1) {
                                out.push_str(&format!("PUSH {}\nPOKE\n", addr));
                            } else {
                                return self.error(format!("Undefined variable in loop step: {}", part1));
                            }
                         } else {
                             // Just an expression?
                             // self.parse_expression?
                             return self.error(format!("Unexpected token in for loop step: {:?}", self.current_token));
                         }
                     },
                     _ => {}, // Empty step?
                 }
                 
                 if self.current_token != Token::RParen { return self.error("Expected )".to_string()); }
                 self.advance();
                 
                 out.push_str(&format!("JMP {}\n", label_start)); // After step, check cond
                 
                 out.push_str(&format!("{}:\n", label_body));
                 self.parse_block(out)?;
                 out.push_str(&format!("JMP {}\n", label_step)); // After body, go to step
                 
                 out.push_str(&format!("{}:\n", label_end));
             },
             Token::Asm => {
                 // asm { "PUSH 1", "ADD" }
                 self.advance();
                 if self.current_token != Token::LBrace { return self.error("Expected { for asm".to_string()); }
                 self.advance();
                 
                 while self.current_token != Token::RBrace && self.current_token != Token::EOF {
                     match &self.current_token {
                         Token::String(s) => {
                             out.push_str(s);
                             out.push('\n');
                             self.advance();
                         },
                         Token::Comma => self.advance(),
                         Token::SemiColon => self.advance(), // Optional
                         _ => return self.error("Expected string literals in asm block".to_string()),
                     }
                 }
                 
                 if self.current_token != Token::RBrace { return self.error("Expected }".to_string()); }
                 self.advance();
             },
             Token::SemiColon => self.advance(),
             _ => return self.error(format!("Unexpected statement token: {:?}", self.current_token)),
        }
        Ok(())
    }

    fn parse_print(&mut self, out: &mut String, newline: bool) -> Result<(), CompileError> {
        if self.current_token != Token::LParen { return self.error("Expected ( for print".to_string()); }
        self.advance();
        
        if self.current_token == Token::RParen {
            self.advance();
            if newline {
                out.push_str("PUSH 10\nPRINT_CHAR\n");
            }
             if self.current_token != Token::SemiColon { 
                 // Missing semicolon after println()
                 println!("DEBUG: Error Pushed. PrevSpan L{} C{}", self.prev_span.line, self.prev_span.col);
                 self.errors.push(CompileError::new("Expected ;".to_string(), self.prev_span));
                 self.synchronize();
                 return Ok(());
             }
             self.advance();
            
            // If it's an empty println(), we still need to print the newline.
            if newline {
                out.push_str("PUSH 10\nPRINT_CHAR\n");
            }
            return Ok(());
        }

       // Check newline logic (Append)
        if newline {
            out.push_str("PUSH 10\nPRINT_CHAR\n");
        }
    
        match &self.current_token {
            Token::String(s) => {
                for c in s.chars() {
                    out.push_str(&format!("PUSH {}\nPRINT_CHAR\n", c as u32));
                }
                self.advance();
            },
            _ => {
                // Try to parse expression (e.g. Number or Variable or Math)
                // Expression leaves result on Stack.
                // We need to print it.
                // OP_PRINT_CHAR prints char. 
                // Issue: If expr is "1 + 2" -> 3. PRINT_CHAR(3) -> ASCII 3 (Wait).
                // We need PRINT_NUM or debug print?
                // User expects `print(123)` -> "123".
                // NuxVM `OP_PRINT_CHAR` handles ASCII.
                // WE DO NOT HAVE `ITOA` (Int to String) in NuxVM yet!
                // Wait, `OP_DEBUG_PRINT` prints value using Rust `println!`.
                // Let's use `OP_DEBUG_PRINT` (0x50) for now if output is number?
                // But `print` implies stdout.
                // Let's implement OP_PRINT_NUM (0x53)?
                // Or user `OP_DEBUG_PRINT` but it says "DEBUG: ...".
                // Let's use OP_DEBUG_PRINT temporarily but removing "DEBUG: " prefix in VM?
                // Or implement simple ITOA in ASM? Hard.
                // Let's add OP_PRINT_VAL (0x53) to VM which prints number.
                
                self.parse_expression(out)?;
                out.push_str("PRINT_VAL\n"); 
            },
        }
        
        if self.current_token != Token::RParen { return self.error("Expected )".to_string()); }
        self.advance();
        
        if newline {
            out.push_str("PUSH 10\nPRINT_CHAR\n");
        }
        
        if self.current_token != Token::SemiColon { 
             self.errors.push(CompileError::new("Expected ;".to_string(), self.prev_span));
             self.synchronize();
             return Ok(());
        }
        self.advance();
        Ok(())
    }
    // --- Expression Parsing ---

    fn parse_expression(&mut self, out: &mut String) -> Result<(), CompileError> {
        // Expr -> Term (+- Term)*
        self.parse_term(out)?;
        
        loop {
            match self.current_token {
                Token::Plus => {
                    self.advance();
                    self.parse_term(out)?;
                    out.push_str("ADD\n");
                },
                Token::Minus => {
                    self.advance();
                    self.parse_term(out)?;
                    out.push_str("SUB\n");
                },
                 Token::EqEq => { self.advance(); self.parse_term(out)?; out.push_str("EQ\n"); },
                 Token::NotEq => { self.advance(); self.parse_term(out)?; out.push_str("NEQ\n"); },
                 Token::Lt => { self.advance(); self.parse_term(out)?; out.push_str("LT\n"); },
                 Token::Gt => { self.advance(); self.parse_term(out)?; out.push_str("GT\n"); },
                 Token::LtEq => { self.advance(); self.parse_term(out)?; out.push_str("LTE\n"); },
                 Token::GtEq => { self.advance(); self.parse_term(out)?; out.push_str("GTE\n"); },
                 Token::And => { self.advance(); self.parse_term(out)?; out.push_str("AND\n"); },
                 Token::Or => { self.advance(); self.parse_term(out)?; out.push_str("OR\n"); },
                _ => break,
            }
        }
        Ok(())
    }

    fn parse_term(&mut self, out: &mut String) -> Result<(), CompileError> {
        // Term -> Factor (*/% Factor)*
        self.parse_factor(out)?;
        
        loop {
            match self.current_token {
                Token::Star => {
                    self.advance();
                    self.parse_factor(out)?;
                    out.push_str("MUL\n");
                },
                Token::Slash => {
                    self.advance();
                    self.parse_factor(out)?;
                    out.push_str("DIV\n");
                },
                Token::Percent => {
                    self.advance();
                    self.parse_factor(out)?;
                    out.push_str("MOD\n");
                },
                _ => break,
            }
        }
        Ok(())
    }

    fn parse_factor(&mut self, out: &mut String) -> Result<(), CompileError> {
        match &self.current_token {
            Token::Number(n) => {
                out.push_str(&format!("PUSH {}\n", n));
                self.advance();
            },
            Token::String(_) => {
                 return self.error("Strings in expressions not fully supported yet".to_string());
            },
            Token::Identifier(name) => {
                let name = name.clone();
                self.advance();
                
                if self.current_token == Token::LParen {
                    // Function Call in Expr!
                    self.advance();
                    if self.current_token != Token::RParen { return self.error("Args not supported".to_string()); }
                    self.advance();
                    out.push_str(&format!("CALL {}\n", name));
                } else if self.current_token == Token::Dot {
                     // Class.Method?
                     self.advance();
                     let part2 = match &self.current_token {
                         Token::Identifier(s) => s.clone(),
                         _ => return self.error("Expected Identifier".to_string()),
                     };
                     self.advance();
                     if self.current_token == Token::LParen {
                        self.advance(); 
                        if self.current_token != Token::RParen { return self.error("Args not supported".to_string()); }
                        self.advance();
                        out.push_str(&format!("CALL {}_{}\n", name, part2));
                     } else {
                         return self.error("Expected Call".to_string());
                     }
                } else {
                    // Variable Access
                    if let Some(addr) = self.var_map.get(&name) {
                        out.push_str(&format!("PUSH {}\nPEEK\n", addr));
                    } else {
                        return self.error(format!("Undefined variable: {}", name));
                    }
                }
            },
            Token::LParen => {
                self.advance();
                self.parse_expression(out)?;
                if self.current_token != Token::RParen { return self.error("Expected )".to_string()); }
                self.advance();
            },
            Token::Input => {
                self.advance();
                if self.current_token != Token::LParen { return self.error("Expected (".to_string()); }
                self.advance();
                if self.current_token != Token::RParen { return self.error("Expected )".to_string()); }
                self.advance();
                out.push_str("INPUT\n");
            },
            _ => return self.error(format!("Unexpected token in expression: {:?}", self.current_token)),
        }
        Ok(())
    }
}
