[workspace]
members = [
    "libainux",
    "programs/ls",
    "programs/cat",
    "programs/ping",
    "programs/nc",
    "programs/wget",
    "programs/deskd",
    "programs/mkdir",
    "programs/rm",
    "programs/rmdir",
    "programs/touch",
    "programs/cp",
    "programs/mv",
    "programs/posixd", 
    "programs/fsd",
    "programs/httpd",
    "programs/hwtest",
    "programs/sh",
    "programs/terminald"
]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
