#ifndef KERNEL_VERSION_H
#define KERNEL_VERSION_H

#define AINUIX_VERSION_MAJOR 1
#define AINUIX_VERSION_MINOR 2
#define AINUIX_VERSION_PATCH 0
#define AINUIX_CODENAME "Aurora"
#define AINUIX_BUILD_DATE __DATE__
#define AINUIX_BUILD_TIME __TIME__

#endif
