/**
 * \file 
 *
 * \brief Common cryptography routines.
 *
 * Cryptography related functions. Note that for strong cryptography the
 * caller should rather use an open implementation of any popular 
 * crypto methods, such as blowfish, etc.
 *
 * These functions are suitable for performing simple user identification
 * and authorisation, not for performing credit-card transactions or 
 * similar.
 * 
 * xcrypto is part of the libxc (Extended C Library) and falls
 * under the relevant copyright license in libxc.
 *
 * \author Lelanthran Krishna Manickum
 *
 * NOTE: xcrypto uses the sha2 implementation under license from 
 * Aaron D. Gifford, license reproduced in full below.
 *
 * _______________________________
 *
 * AUTHOR:	Aaron D. Gifford - http://www.aarongifford.com/
 * 
 * Copyright (c) 2000-2001, Aaron D. Gifford
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTOR(S) ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTOR(S) BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */

#include <stdio.h>

#ifdef PLATFORM_WINDOWS
#include <windows.h>
#include <Wincrypt.h>
#endif

#include "xerror/xerror.h"
#include "xcrypto/xcrypto.h"

#include "xcrypto/sha2.h"

#ifndef OSLIBTYPE 
#error OSLIBTYPE not defined
#endif

#if (!defined PLATFORM_POSIX && !defined PLATFORM_WINDOWS && !defined PLATFORM)
#error PLATFORM not defined
#endif

/**
 * \brief Returns a cryptographically secure pseudorandom sequence of bytes
 *
 * Return a pseudorandom sequence of bytes, guaranteed to be at least as 
 * secure for cryptography purposes as the platform allows. On posix 
 * platforms the sequence of random bytes is generated by reading from
 * /dev/random. On Windows the sequence of random bytes is generated
 * by using the CryptoAPI available on Win32.
 *
 * The return value is the number of bytes that were randomly generated
 * or (size_t)-1 if the function was unsuccessful.
 *
 * @param[out] buffer The buffer to hold the random sequence of bytes
 * @param[in] num_bytes The number of random bytes to generate and store
 *    in the buffer \a buffer
 *
 * @return On success the buffer \a buffer is populated with a sequence of
 * cryptographically secure random bytes and the number of bytes generated
 * is returned. On failure (size_t)-1 is returned.
 */
size_t xcrypto_random (uint8_t *buffer, size_t num_bytes)
{
#ifdef PLATFORM_POSIX
   FILE *devrand = fopen ("/dev/random", "r");
   if (!devrand) {
      XLOG ("Unable to read /dev/random\n");
      return (size_t)-1;
   }
   if (fread (buffer, 1, num_bytes, devrand)<num_bytes) {
      return (size_t)-1;
   }
   fclose (devrand);
   return num_bytes;
#endif
#ifdef PLATFORM_WINDOWS
   memset (buffer, 0, num_bytes);
   static unsigned char lpMsgBuf[4096];
   size_t dw;
   size_t ret = num_bytes;
   HCRYPTPROV hProv;
   if (!CryptAcquireContext(&hProv, NULL, NULL,
                            PROV_RSA_FULL, CRYPT_VERIFYCONTEXT)) {
      dw = GetLastError ();
      FormatMessage(
        FORMAT_MESSAGE_ALLOCATE_BUFFER | 
        FORMAT_MESSAGE_FROM_SYSTEM |
        FORMAT_MESSAGE_IGNORE_INSERTS,
        NULL,
        dw,
        MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
        (LPTSTR) &lpMsgBuf,
        0, NULL );
      XLOG ("Error: %s\n", lpMsgBuf);
      return 0;
   }


   if (!CryptGenRandom( hProv, num_bytes, buffer)) {
      dw = GetLastError ();
      FormatMessage(
        FORMAT_MESSAGE_ALLOCATE_BUFFER | 
        FORMAT_MESSAGE_FROM_SYSTEM |
        FORMAT_MESSAGE_IGNORE_INSERTS,
        NULL,
        dw,
        MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
        (LPTSTR) &lpMsgBuf,
        0, NULL );
      XLOG ("Error: %s\n", lpMsgBuf);
      ret = 0;
   }

   if (!CryptReleaseContext(hProv, 0)) {
      dw = GetLastError ();
      FormatMessage(
        FORMAT_MESSAGE_ALLOCATE_BUFFER | 
        FORMAT_MESSAGE_FROM_SYSTEM |
        FORMAT_MESSAGE_IGNORE_INSERTS,
        NULL,
        dw,
        MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
        (LPTSTR) &lpMsgBuf,
        0, NULL );
      XLOG ("Error: %s\n", lpMsgBuf);
      ret = 0;
   }
   return ret;
#endif
}

/**
 * \brief Generates the SHA2-256 hash of the given buffer
 *
 * Generates the SHA2-256 hash of the buffer \a buffer. The length
 * of the buffer \a buffer is specified in \a num_bytes. The hash is
 * returned in a malloced block of memory that must be freed by the caller.
 *
 * @param[in] buffer The buffer containing the data to hash
 * @param[in] num_bytes The number of bytes in the buffer \a buffer
 *
 * @return On success a freshly allocated block of memory of exactly
 * 65 bytes containing the SHA2-256 hash of \a buffer is returned. The caller
 * must free this buffer. The buffer is the 64-byte C-string representation 
 * of the hash of \a buffer, with a single \a NULL terminating the string.
  * On failure \a NULL is returned.
 */
char *xcrypto_hash (const uint8_t *buffer, size_t num_bytes)
{
   char *ret = malloc (65);
   if (!ret) return NULL;
   memset (ret, 0, 65);

   SHA256_CTX ctx256;
   SHA256_Init(&ctx256);
   SHA256_Update(&ctx256, (unsigned char*)buffer, num_bytes);
   SHA256_End(&ctx256, ret);
   return ret;
}
