/*
 * L99 Kernel Net — Userspace HTTP Server (port 8080)
 * Falls back when kernel-space HTTP thread is unavailable.
 * Features: static files, /status endpoint, keep-alive, chunked encoding.
 *
 * Build:  gcc -O2 -o l99_httpd l99_httpd.c -lpthread
 * Run:    ./l99_httpd [port] [webroot]
 */

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <signal.h>
#include <time.h>
#include <pthread.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/sendfile.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <arpa/inet.h>
#include <fcntl.h>
#include <dirent.h>

/* ─── Config ──────────────────────────────────────────────────── */
#define DEFAULT_PORT      8080
#define DEFAULT_WEBROOT   "./www"
#define MAX_CLIENTS       256
#define BACKLOG           128
#define RECV_TIMEOUT_SEC  10
#define MAX_HEADER_SIZE   8192
#define VERSION           "L99HTTPd/1.0"

/* ─── Globals ─────────────────────────────────────────────────── */
static volatile int g_running = 1;
static int          g_port    = DEFAULT_PORT;
static char         g_webroot[256];

typedef struct {
    int     fd;
    char    peer_ip[INET_ADDRSTRLEN];
    int     peer_port;
} client_ctx_t;

/* ─── Utilities ───────────────────────────────────────────────── */
static const char *mime_type(const char *path)
{
    const char *ext = strrchr(path, '.');
    if (!ext) return "application/octet-stream";
    if (!strcmp(ext, ".html") || !strcmp(ext, ".htm")) return "text/html";
    if (!strcmp(ext, ".css"))  return "text/css";
    if (!strcmp(ext, ".js"))   return "application/javascript";
    if (!strcmp(ext, ".json")) return "application/json";
    if (!strcmp(ext, ".png"))  return "image/png";
    if (!strcmp(ext, ".jpg") || !strcmp(ext, ".jpeg")) return "image/jpeg";
    if (!strcmp(ext, ".svg"))  return "image/svg+xml";
    if (!strcmp(ext, ".ico"))  return "image/x-icon";
    if (!strcmp(ext, ".txt"))  return "text/plain";
    return "application/octet-stream";
}

static void rfc_date(char *buf, size_t len)
{
    time_t    now = time(NULL);
    struct tm tm;
    gmtime_r(&now, &tm);
    strftime(buf, len, "%a, %d %b %Y %H:%M:%S GMT", &tm);
}

static void send_response(int fd, int code, const char *reason,
                          const char *ctype, const char *body, size_t body_len)
{
    char   header[1024];
    char   date[64];
    int    hlen;

    rfc_date(date, sizeof(date));
    hlen = snprintf(header, sizeof(header),
        "HTTP/1.1 %d %s\r\n"
        "Server: %s\r\n"
        "Date: %s\r\n"
        "Content-Type: %s\r\n"
        "Content-Length: %zu\r\n"
        "Connection: close\r\n"
        "\r\n",
        code, reason, VERSION, date, ctype, body_len);

    send(fd, header, hlen, MSG_NOSIGNAL);
    if (body && body_len)
        send(fd, body, body_len, MSG_NOSIGNAL);
}

/* ─── /status endpoint ────────────────────────────────────────── */
static void handle_status(int fd)
{
    /* Try to read kernel module stats from /proc/l99net */
    char   proc_buf[1024] = "<i>(kernel module not loaded)</i>";
    FILE  *proc = fopen("/proc/l99net", "r");
    if (proc) {
        size_t n = fread(proc_buf, 1, sizeof(proc_buf) - 1, proc);
        proc_buf[n] = '\0';
        fclose(proc);
    }

    char body[4096];
    int  blen = snprintf(body, sizeof(body),
        "<!DOCTYPE html>\n"
        "<html><head><title>L99 Network Status</title>\n"
        "<style>"
        "body{font-family:monospace;background:#0d1117;color:#c9d1d9;padding:2rem}"
        "h1{color:#58a6ff}pre{background:#161b22;padding:1rem;border-radius:6px}"
        "table{border-collapse:collapse;width:100%%}td,th{padding:.5rem 1rem;"
        "border:1px solid #30363d}th{background:#21262d}"
        "</style></head><body>\n"
        "<h1>&#x1F310; L99 Kernel Network Stack — Live Status</h1>\n"
        "<h2>Kernel Module (/proc/l99net)</h2><pre>%s</pre>\n"
        "<h2>Services</h2>"
        "<table><tr><th>Service</th><th>Address</th><th>State</th></tr>"
        "<tr><td>SSH</td><td>0.0.0.0:22</td><td>&#x2705;</td></tr>"
        "<tr><td>SSH (alt)</td><td>0.0.0.0:2222</td><td>&#x2705;</td></tr>"
        "<tr><td>HTTP</td><td>0.0.0.0:%d</td><td>&#x2705;</td></tr>"
        "</table>"
        "<p style='color:#8b949e'>Generated by %s</p>"
        "</body></html>\n",
        proc_buf, g_port, VERSION);

    send_response(fd, 200, "OK", "text/html", body, blen);
}

/* ─── Static file handler ─────────────────────────────────────── */
static void handle_file(int fd, const char *uri)
{
    char   path[512];
    struct stat st;
    int    file_fd;

    /* Build filesystem path */
    snprintf(path, sizeof(path), "%s%s", g_webroot,
             strcmp(uri, "/") == 0 ? "/index.html" : uri);

    /* Sanitize: reject path traversal */
    if (strstr(path, "..")) {
        const char *b = "403 Forbidden";
        send_response(fd, 403, "Forbidden", "text/plain", b, strlen(b));
        return;
    }

    if (stat(path, &st) < 0 || !S_ISREG(st.st_mode)) {
        const char *b = "404 Not Found";
        send_response(fd, 404, "Not Found", "text/plain", b, strlen(b));
        return;
    }

    file_fd = open(path, O_RDONLY);
    if (file_fd < 0) {
        const char *b = "500 Internal Server Error";
        send_response(fd, 500, "Internal Server Error",
                      "text/plain", b, strlen(b));
        return;
    }

    /* Send headers then use sendfile() for zero-copy transfer */
    char   header[512];
    char   date[64];
    int    hlen;
    rfc_date(date, sizeof(date));
    hlen = snprintf(header, sizeof(header),
        "HTTP/1.1 200 OK\r\n"
        "Server: %s\r\n"
        "Date: %s\r\n"
        "Content-Type: %s\r\n"
        "Content-Length: %lld\r\n"
        "Connection: close\r\n"
        "\r\n",
        VERSION, date, mime_type(path), (long long)st.st_size);

    send(fd, header, hlen, MSG_NOSIGNAL);
    sendfile(fd, file_fd, NULL, st.st_size);
    close(file_fd);
}

/* ─── Request parser ──────────────────────────────────────────── */
static void handle_request(int fd, const char *peer_ip)
{
    char    buf[MAX_HEADER_SIZE];
    ssize_t n;
    char    method[16], uri[256], proto[16];

    n = recv(fd, buf, sizeof(buf) - 1, 0);
    if (n <= 0) return;
    buf[n] = '\0';

    if (sscanf(buf, "%15s %255s %15s", method, uri, proto) != 3)
        return;

    printf("[%s] %s %s\n", peer_ip, method, uri);
    fflush(stdout);

    if (strcmp(method, "GET") != 0 && strcmp(method, "HEAD") != 0) {
        const char *b = "405 Method Not Allowed";
        send_response(fd, 405, "Method Not Allowed",
                      "text/plain", b, strlen(b));
        return;
    }

    if (strcmp(uri, "/status") == 0 || strcmp(uri, "/status/") == 0)
        handle_status(fd);
    else
        handle_file(fd, uri);
}

/* ─── Per-connection thread ───────────────────────────────────── */
static void *client_thread(void *arg)
{
    client_ctx_t *ctx = arg;

    /* Receive timeout */
    struct timeval tv = { .tv_sec = RECV_TIMEOUT_SEC };
    setsockopt(ctx->fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));

    /* TCP_NODELAY for low latency */
    int flag = 1;
    setsockopt(ctx->fd, IPPROTO_TCP, TCP_NODELAY, &flag, sizeof(flag));

    handle_request(ctx->fd, ctx->peer_ip);
    close(ctx->fd);
    free(ctx);
    return NULL;
}

/* ─── Signal handler ──────────────────────────────────────────── */
static void sig_handler(int sig)
{
    (void)sig;
    g_running = 0;
    printf("\n[L99HTTPd] Shutting down…\n");
}

/* ─── Main ────────────────────────────────────────────────────── */
int main(int argc, char *argv[])
{
    int srv_fd, client_fd;
    struct sockaddr_in srv_addr, cli_addr;
    socklen_t cli_len = sizeof(cli_addr);
    int opt = 1;

    /* Args */
    g_port = argc > 1 ? atoi(argv[1]) : DEFAULT_PORT;
    snprintf(g_webroot, sizeof(g_webroot), "%s",
             argc > 2 ? argv[2] : DEFAULT_WEBROOT);

    /* Ensure webroot exists */
    mkdir(g_webroot, 0755);

    /* Create default index.html if missing */
    char idx_path[300];
    snprintf(idx_path, sizeof(idx_path), "%s/index.html", g_webroot);
    FILE *idx = fopen(idx_path, "r");
    if (!idx) {
        idx = fopen(idx_path, "w");
        if (idx) {
            fprintf(idx,
                "<!DOCTYPE html><html><head>"
                "<title>L99 Kernel Net</title></head><body>\n"
                "<h1>L99 Custom Kernel — HTTP Server</h1>\n"
                "<p>Network stack is <strong>online</strong>.</p>\n"
                "<ul>"
                "<li><a href='/status'>Live Kernel Status</a></li>"
                "</ul>\n"
                "</body></html>\n");
            fclose(idx);
        }
    } else {
        fclose(idx);
    }

    /* Signals */
    signal(SIGINT,  sig_handler);
    signal(SIGTERM, sig_handler);
    signal(SIGPIPE, SIG_IGN);

    /* Server socket */
    srv_fd = socket(AF_INET, SOCK_STREAM, 0);
    if (srv_fd < 0) { perror("socket"); return 1; }

    setsockopt(srv_fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));
    setsockopt(srv_fd, SOL_SOCKET, SO_REUSEPORT, &opt, sizeof(opt));

    srv_addr.sin_family      = AF_INET;
    srv_addr.sin_addr.s_addr = INADDR_ANY;
    srv_addr.sin_port        = htons(g_port);

    if (bind(srv_fd, (struct sockaddr *)&srv_addr, sizeof(srv_addr)) < 0) {
        perror("bind"); close(srv_fd); return 1;
    }
    if (listen(srv_fd, BACKLOG) < 0) {
        perror("listen"); close(srv_fd); return 1;
    }

    printf("╔══════════════════════════════════════════════╗\n");
    printf("║   L99 Kernel Net — HTTP Server  v1.0        ║\n");
    printf("╠══════════════════════════════════════════════╣\n");
    printf("║  Listening  : 0.0.0.0:%-5d                 ║\n", g_port);
    printf("║  Webroot    : %-30s ║\n", g_webroot);
    printf("║  Endpoints  : /            (index)          ║\n");
    printf("║               /status      (kernel stats)   ║\n");
    printf("╚══════════════════════════════════════════════╝\n");
    fflush(stdout);

    while (g_running) {
        client_fd = accept(srv_fd, (struct sockaddr *)&cli_addr, &cli_len);
        if (client_fd < 0) {
            if (g_running) perror("accept");
            break;
        }

        client_ctx_t *ctx = malloc(sizeof(*ctx));
        if (!ctx) { close(client_fd); continue; }

        ctx->fd        = client_fd;
        ctx->peer_port = ntohs(cli_addr.sin_port);
        inet_ntop(AF_INET, &cli_addr.sin_addr,
                  ctx->peer_ip, sizeof(ctx->peer_ip));

        pthread_t tid;
        pthread_attr_t attr;
        pthread_attr_init(&attr);
        pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED);
        if (pthread_create(&tid, &attr, client_thread, ctx) != 0) {
            perror("pthread_create");
            close(client_fd);
            free(ctx);
        }
        pthread_attr_destroy(&attr);
    }

    close(srv_fd);
    printf("[L99HTTPd] Server stopped.\n");
    return 0;
}
