/**
 * \file 
 *
 * \brief File and Filesystem manipulation routines
 *
 * A library to ease usage of the filesystem, offering automated file backups,
 * file locking, file deletion and renaming and file attributes.
 *
 * xfile is part of the libxc (Extended C Library) and falls
 * under the relevant copyright license in libxc.
 *
 * \author Lelanthran Krishna Manickum
 *
 */

#include <errno.h>
#define _POSIX_C_SOURCE   1   // For fdopen

#if defined (PLATFORM_MSYS) || (PLATFORM_WINDOWS)
#define PLATFORM_WINDOWS   1
#define _WIN32_WINNT       0x0501
#include <windows.h>
#include <winbase.h>
#endif

#ifdef PLATFORM_POSIX
#endif

#include <stdio.h>
#include <time.h>
#include <errno.h>

#include <sys/types.h>
#include <dirent.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <regex.h>

#include "xfile/xfile.h"
#include "xlex/xlex.h"
#include "xstring/xstring.h"
#include "xerror/xerror.h"
#include "xcrypto/xcrypto.h"

static int safe_readdir (DIR *dirp, struct dirent *entry, struct dirent **result)
{
#ifdef PLATFORM_WINDOWS
   *result = NULL;
   struct dirent *retval = readdir (dirp);
   if (!retval) return -1;

   memcpy (entry, retval, sizeof *entry);
   *result = retval;
   return 0;
#else
   return readdir_r (dirp, entry, result);
#endif
}

/**
 * \brief Create a temporary file
 *
 * Creates a temporary file in the directory \a dirname and returns the
 * name of this newly created file. The file is guaranteed to have a unique
 * and random name within \a dirname. The name that is returned is freshly
 * allocated so the caller should free this return value after using it.
 * If \a dirname is \a NULL the file is created in the current directory.
 *
 * The caller can use \a fopen() or similar to open the file for reading.
 * The file is created with read and write permissions for the caller.
 * 
 * NOTE: The name that is created is random and cryptographically secure  
 * and therefore unguessable (within the limits of the systems 
 * Cryptographically Secure Pseudo-Random Number Generator). Due to usage
 * of the system's CSPRNG, generation of the filename may take time while
 * entropy is generated by the system.
 *
 * \sa xerror.c, XLOG()
 *
 * @param[in] dirname The name of the directory to create this file in.
 *    if \a dirname is NULL then the file is created in the current 
 *    directory
 *
 * @return On success a newly allocated string containing the filename
 * of the temporary file just created is returned. The caller must free
 * this returned string.
 * On failure \a NULL is returned; diagnostics will be logged to the
 * system logfile using XLOG.
 *
 * \a Example
 * \verbatim
   int main (void)
   {
      char *tfile = xfile_tmpname (NULL);
      if (tfile) {
         printf ("Created unique file %s\n", tfile);
         free (tfile);
      } else {
         printf ("Unable to create unique file\n");
      }
      return EXIT_SUCCESS;
   }
  \endverbatim
 */
char *xfile_tmpname (const char *dirname)
{
   if (!dirname) dirname = ".";
   uint8_t randbytes[15];
   char tmpname[31], *newname = NULL;
   int newfd = -1;
   do {
      size_t i;
      xcrypto_random (randbytes, sizeof randbytes);
      for (i=0; i<sizeof randbytes; i++) {
         sprintf (&tmpname[i*2], "%02x", randbytes[i]);
      }
      tmpname[i] = 0;
      newname = xstr_cat (dirname, "/", tmpname, NULL);
      if (!newname) {
         XLOG ("Unable to allocate memory for newname\n");
         return NULL;
      }
      newfd = creat (newname, S_IRUSR | S_IWUSR);
      if (newfd==-1) {
         if (errno!=EEXIST) {
            XLOG ("Unable to create newfile %s: %m\n", newname);
            free (newname);
            return NULL;
         }
      }
   } while (newfd==-1);
   close (newfd);
   return newname;
}

/**
 * \brief Atomically create a file and fail if file already exists.
 *
 * Atomically create file \a filename in directory \a dirname,  \a if 
 * \a and \a only \a if the file doesn't already exist. If the file
 * exists then a failure is logged to the system log using XLOG() and
 * NULL is returned. This function is suitable for generating and testing
 * for lockfiles.
 *
 * If the file does not exist and was created atomically, then a writable
 * stream to this file is returned as a FILE *. This function differs
 * from calling the posix function \a open() with flags O_CREAT | O_EXCL
 * in that this function is safe to use on NFS mounted volumes.
 *
 * NOTE: This function uses the systems random and cryptographically secure  
 * pseudorandom number generator.  Due to usage
 * of the systems CSPRNG, creation of the filename may take time while
 * entropy is generated by the system.
 *
 * \sa xerror.c, XLOG()
 *
 * @param[in] dirname The name of the directory to create this file in.
 *    if \a dirname is NULL then the file is created in the current 
 *    directory
 * @param[in] filename The name of the file to create
 *
 * @return On success a FILE * suitable for writing to and reading from
 * is returned. The caller must call fclose() on the return value.
 * On failure \a NULL is returned; diagnostics will be logged to the
 * system logfile using XLOG.
 *
 * \a Example
 * \verbatim
   int main (void)
   {
      FILE *tfile = xfile_atomic ("/tmp", "testapp.lock");
      if (tfile) {
         fprintf (tfile, "Created lockfile %s\n", "testapp.lock");
         fclose (tfile);
      } else {
         printf ("Unable to create lockfile\n");
      }
      return EXIT_SUCCESS;
   }
  \endverbatim
 */
FILE *xfile_atomic (const char *dirname, const char *filename)
{
   if (!filename) return NULL;
   // Create full pathname of filename
   char *fpathname = xstr_cat (dirname, "/", filename, NULL);
   if (!fpathname) {
      XLOG ("Unable to allocate memory for full pathname %s/%s\n", 
            dirname, filename);
      return NULL;
   }

   // Create a new file in dirname
   char *tmpfname = xfile_tmpname (dirname);
   if (!tmpfname) {
      XLOG ("Unable to create tempfile in %s: %m\n", dirname);
      free (fpathname);
      return NULL;
   }

   // Link it to the atomic file pathname
   errno = 0;
#ifdef PLATFORM_POSIX
   if (link (tmpfname, fpathname)==0) {
#endif
#if defined (PLATFORM_MSYS) || (PLATFORM_WINDOWS)
   if (CreateHardLink (fpathname, tmpfname, NULL)!=0) {
#endif
      // It didn't exist, so we have atomically created it
      FILE *ret = fopen (fpathname, "w+");
      XLOG ("Removing %s:1\n", tmpfname);
      remove (tmpfname);
      free (tmpfname);
      free (fpathname);
      return ret;
   }
   // If we got here then the file already exists
   XLOG ("Atomic file creation failed %s->%s : %m\n", tmpfname, fpathname);
   XLOG ("Removing %s:2\n", tmpfname);
   remove (tmpfname);
   free (tmpfname);
   free (fpathname);

   return NULL;
}

/**
 * \brief Open a file for writing, backing it up if it already exists
 *
 * Open the file \a filename for writing. If the file already exists it
 * is backed-up using the extension \a ext and a single digit [0-9].
 * If filename.ext.[0-9] exists, then it is copied to the next higher number
 * to a maximum of 9. For example, if \a filename is "testfile" and \a ext
 * is "bak" and the files "testfile.bak.0' to "testfile.bak.9" exists, then
 * \a xfile_open_with_backup() will copy "testfile.bak.8" to "testfile.bak.9",
 * then copy "testfile.bak.7" to "testfile.bak.8", etc.
 * The existing file "testfile" will be copied to "testfile.bak.0".
 * 
 * The file "testfile" is then opened for writing, and a FILE * is returned
 * to the caller. The caller must call \a fclose() on the returned FILE *.
 * 
 * Errors that occur will be logged to the system log using XLOG() and
 * NULL will be returned in the event of an error.
 *
 * \sa xerror.c, XLOG()
 *
 * @param[in] filename The file to open for writing. If no file is provided
 *  then \a NULL is returned
 * @param[in] ext The extension to use when creating the backups. If \a ext
 * is NULL then no extension will be used, only digits
 *
 * @return On success a FILE * suitable for writing to the file \a filename
 * is returned. The caller must call fclose() on the return value.
 * On failure \a NULL is returned; diagnostics will be logged to the
 * system logfile using XLOG.
 *
 * \a Example
 * \verbatim
   FILE *tmp = xfile_open_with_backup ("testfile.new", "bak");
   // testfile.new.bak.0 will be created if testfile.new exists
   // testfile.new.bak.1 will be created if testfile.new.bak.0 exists
   // ... etc ...
   // 
   if (!tmp) {
      printf ("Could not open testfile.new for writing: %m\n");
   } else {
      fprintf (tmp, "written\n");
      fclose (tmp);
   }
  \endverbatim
 */
FILE *xfile_open_with_backup (const char *filename, const char *ext)
{
   // if filename exists, copy to filename.ext.1
   // if filename.ext.1 exists, copy to filename.ext.2
   // ad infinitum
   int errors = 0;
   if (!filename) return NULL;
   if (!ext) ext = "";
   // Generate array of filenames
   char *fnames[10];
   size_t filenamesize = (strlen (filename) + 1 +
                          strlen (ext) + 1 +
                          strlen ("1") + 1);
   for (size_t i=0; i<sizeof fnames/sizeof fnames[0]; i++) {
      fnames[i] = malloc (filenamesize);
      if (!fnames[i]) {
         XLOG ("Unable to allocate memory for %s.%s.%i\n", 
               filename, ext, i);
      }
      sprintf (fnames[i], "%s.%s.%zu", filename, ext, i);
   }
   // Copy each filename[i] to filename[i+1]
   for (size_t i=sizeof fnames/sizeof fnames[0]; i>1;  i--) {
      if (xfile_copy (fnames[i-2], fnames[i-1], 0, NULL)==(uint64_t)-1) {
         // XLOG ("Unable to copy %s -> %s: %m\n", fnames[i-2], fnames[i-1]);
      }
      remove (fnames[i-2]);
      free (fnames[i-1]);
   }
   if (xfile_copy (filename, fnames[0], 0, NULL)==(uint64_t)-1) {
      XLOG ("Unable to copy %s -> %s: %m\n", filename, fnames[0]);
      // errors++; // NOt necessarily an error if source doesn't exist
   }
   free (fnames[0]);
   if (errors) return NULL;
   FILE *ret = fopen (filename, "w");
   if (!ret) {
      XLOG ("Unable to open %s for writing: %m\n", filename);
   }
   return ret;
}

/*
char **xfile_list (const char *dirname)
{
   // TODO
}
*/

/**
 * \brief Provides some metadata about a file
 *
 * Provides some metadata about a file and returns it in a freshly allocated
 * xfile_stat_t structure, as documented below. The caller must free the
 * return value using \a free(return_value->name) and \a free(return_value)
 * \verbatim
enum xfile_type_t {
   stat_REG = 1,
   stat_DIR,
   stat_OTHER,
};
struct xfile_stat_t {
   xfile_type_t type;      // whether regular file, directory or something else
   uint64_t size;          // size of the file in bytes
   size_t link_count;      // number of names this file has (hard links)
   time_t last_access;     // timestamp of last access
   time_t last_modified;   // timestamp of last modification
   char  *name;            // One name of this file; there might be more
};
  \endverbatim
 *
 * Note that the \a name field of the xfile_stat_t structure is allocated
 * using \a free(). The caller must free this field before freeing the 
 * structure.
 *
 * \sa xerror.c, XLOG()
 *
 * @param[in] pathname The file/dir to get metadata on.
 *
 * @return On success an xfile_stat_t * is returned, which the caller must
 * free using free().
 * On failure \a NULL is returned; diagnostics will be logged to the
 * system logfile using XLOG.
 *
 * \a Example
 * \verbatim
   // TODO put in an example
  \endverbatim
 */
xfile_stat_t *xfile_stat (const char *pathname)
{
   struct stat buffer;
   if (stat (pathname, &buffer)<0) return NULL;
   xfile_stat_t *ret = malloc (sizeof *ret);
   if (!ret) return NULL;

   ret->name = xstr_dup (pathname);
   if (!ret->name) {
      free (ret);
      return NULL;
   }

   ret->type = stat_OTHER;
   if (S_ISREG (buffer.st_mode)) ret->type = stat_REG;
   if (S_ISDIR (buffer.st_mode)) ret->type = stat_DIR;

   ret->size = buffer.st_size;
   ret->link_count = buffer.st_nlink;
   ret->last_access = buffer.st_atime;
   ret->last_modified = buffer.st_mtime;
   return ret;
}

/**
 * \brief File copy
 *
 * Copy the file specified with filename \a source to the filename
 * specified by \a dest. If \a dest already exists it will be overwritten.
 * If \a dest does not exist it will be created with default permissions
 * (not with the permissions of \a source).
 *
 * The parameter \a bufsize controls how many bytes at a time are copied.
 * If \a bufsize is set to zero then a default is used instead.
 * After every copy of \a bufsize to the new file \a dest, the function
 * \a progress, if non-NULL, will be called with the number of bytes already
 * copied. If
 * \a progress returns non-zero then the function will end with a diagnostic
 * logged to the system log using XLOG() and the copy operation will be 
 * cancelled. Upon cancellation \a dest, if it exists, will be deleted. 
* If \a progress is \a NULL, then it is ignored.
 *
 * Note that this function will only copy a filename to a new filename, so
 * if \a dest is a directory name then this function will fail.
 *
 * \sa xerror.c, XLOG()
 *
 * @param[in] source The sourcefile to copy
 * @param[in] dest The destination of the new file
 * @param[in] bufsize The buffer size to use when copying
 * @param[in] progress A callback function to notify the caller of the progress
 *    that is being made and to give the caller a chance to cancel the 
 *    copy operation
 *
 * @return On success the number of bytes copied is returned. On failure
 *  (uint64_t)-1 is returned and a diagnostic will be logged to the system
 * log using XLOG().
 *
 * \a Example
 * \verbatim
volatile int stop_copy = 0;

void signal_h (int n)
{
   if (n==SIGINT) stop_copy = 1;
}

// Print out the progress as we copy, and cancel the copy if
// signal_h set stop_copy to 1.
int progress_cb (uint64_t copied)
{
   printf ("\rBytes copied:  %zi", copied);
   if (stop_copy==1) {
      printf ("User pressed CTRL-C, cancelling the copy\n");
   }
   return stop_copy;
}

int main (void)
{
   // If user presses ctrl-c, this function will run
   signal (SIGINT, signal_h); 
   // Start the copy, ctrl-c will end it
   xfile_copy ("testfile", "testfile.new", 1024, progress_cb);
   printf ("\n");
   return EXIT_SUCCESS;
}

  \endverbatim
 */
uint64_t xfile_copy (const char *source, const char *dest,
                     size_t bufsize, int (*progress) (uint64_t))
{
   uint64_t ret = 0;
   unsigned char *buffer = NULL;
   FILE *in = NULL, *out = NULL;
   if (!dest) {
      XLOG ("dest==NULL");
      goto error;
   }
   if (!source) {
      XLOG ("source==NULL");
      goto error;
   }
   if (bufsize==0) bufsize = (8192 * 1024);
   in = fopen (source, "r");
   if (!in) {
      XLOG ("Cannot open %s for reading: %m\n", source);
      goto error;
   }
   out = fopen (dest, "w");
   if (!out) {
      XLOG ("Cannot open %s for writing: %m\n", dest);
      goto error;
   }
   buffer = malloc (bufsize);
   if (!buffer) {
      XLOG ("Unable to allocate %bytes for file copy\n", bufsize);
      goto error;
   }

   while (!feof (in) && !ferror (in)) {
      size_t bytes_read = fread (buffer, 1, bufsize, in);
      size_t bytes_written = 0;
      do {
         bytes_written += fwrite (&buffer[bytes_written], 1,
                                  bytes_read - bytes_written, out);
      } while (bytes_written<bytes_read);
      ret += bytes_written;
      if (progress && progress (ret)) {
         XLOG ("Copy operation interrupted by caller after %li bytes\n", ret);
         fclose (in); fclose (out);
         remove (dest);
         free (buffer);
         return (uint64_t)-1;
      }
   }
   fclose (in);
   fclose (out);
   free (buffer);
   return ret;
error:
   if (in) fclose (in);
   if (out) fclose (out);
   if (buffer) free (buffer);
   return (uint64_t)-1;
}

/**
 * \brief Tests if the given file can be opened for reading
 *
 * Attempts to open the file \a filename for reading; file \a filename
 * is non-destructively opened and then closed. No changes are made to
 * the file \a filename.
 *
 * If the file specified by \a filename doesn't exist or is otherwise
 * unreadable (permissions might not allow, for example), then false
 * is returned. If the file was successfully opened and closed, true is
 * returned.
 *
 * NOTE: Many of the libxc functions which require a filename as an argument
 * will attempt to open the given filename and return failure if the attempt
 * to open the file was unsuccessful. A well-behaved program will use
 * xfile_readable() to first ensure that the file exists and can be 
 * read before calling such functions.
 *
 * \sa xstr_readfile(), xfile_writable()
 *
 * @param[in] filename The filename to test for reading
 *
 * @return If the file \a filename is successfully opened for reading 
 * then true is returned.
 * If any errors occurred that prevented the successful opening and closing
 * of the file \a filename for reading then false is returned.
 *
 * \a Example:
 * \verbatim
   int main (void)
   {
      if (xfile_readable ("input.txt")) {
         printf ("file input.txt is readable\n");
      } else {
         printf ("file input.txt is not readable\n");
      }
      ... 
      return EXIT_SUCCESS;
   }
   \endverbatim
 */ 
bool xfile_readable (const char *filename)
{
   if (!filename) return false;
   FILE *tmp = fopen (filename, "r");
   if (!tmp) return false;
   fclose (tmp);
   return true;
}

/**
 * \brief Tests if the given file can opened for writing
 *
 * Attempts to open the file \a filename for writing; file \a filename
 * is non-destructively opened and then closed. No changes are made to
 * the file \a filename.
 *
 * If the file specified by \a filename can neither be created for
 * writing nor opened for writing (permissions might not allow writing,
 * for example), then false
 * is returned. If the file was successfully opened and closed, true is
 * returned and the file is left unchanged.
 *
 * NOTE: Before writing any file, a well-behaved program will first
 * use xfile_readable() to check if the file already exists. If it does
 * then the user should be prompted to confirm that they are sure that they
 * want to overwrite the existing file.
 *
 * \sa xstr_readfile(), xfile_readable()
 *
 * @param[in] filename The filename to test for writing
 *
 * @return If the file \a filename is successfully opened for writing 
 * then true is returned.
 * If any errors occurred that prevented the successful opening and closing
 * of the file \a filename for writing then false is returned.
 *
 * \a Example:
 * \verbatim
   int main (void)
   {
      if (file_writable ("output.txt")) {
         printf ("file output.txt is writable\n");
      } else {
         printf ("file output.txt is not writable\n");
      }
      ... 
      return EXIT_SUCCESS;
   }
   \endverbatim
 */ 
bool xfile_writable (const char *filename)
{
   if (!filename) return false;
   FILE *tmp = fopen (filename, "a");
   if (!tmp) return false;
   fclose (tmp);
   return true;
}


/**
 * \brief Create a directory
 *
 * Creates the directory named by \a path. If the given path has more
 * than one directory named, all the parents will be created so ensure
 * creation of the directory named.
 *
 *
 * \sa xfile_rm(), \sa xfile_find()
 *
 * @param[in] path The directory to create.
 *
 * @return If the path \a path is successfully created
 * then true is returned.
 * If any errors occurred that prevented the successful creation
 * of the path \a path.
 *
 * \a Example:
 * \verbatim
   int main (void)
   {
      if (xfile_mkdir ("newdir1/newdir2/newdir3")) {
         printf ("Directories newdir1/newdir2/newdir3 created\n");
      } else {
         printf ("Unable to create directory newdir\n");
      }
      ... 
      return EXIT_SUCCESS;
   }
   \endverbatim
 */
bool xfile_mkdir (char *filename, char *flags)
{
   bool retval = false;
   int rc;
   char *copy = xstr_dup (filename);
   if (!copy)
      goto errorexit;

   if (strchr (flags, 'p')) {

      char *tmp = strchr (copy, '/');
      while (tmp && *tmp) {
         *tmp = 0;
         rc = *copy ? mkdir (copy, 0777) : 0;
         *tmp++ = '/';
         if (rc!=0 && errno!=EEXIST)
            goto errorexit;
         tmp = strchr (tmp, '/');
      }

   }

   rc = mkdir (filename, 0777);
   if (rc==0)
      retval = true;
   if (errno==EEXIST)
      retval = true;

errorexit:
   free (copy);
   return retval;
}

static void free_fstat (xfile_stat_t *f)
{
   if (f) {
      free (f->name);
   }
   free (f);
}

/**
 * \brief Removes a file or directory, optionally recursive
 *
 * Removes the file or directory named by \a pathname, using flags to specify 
 * behaviour. If \a pathname is an empty directory it will be removed. If
 * directory is non-empty, then no action will be taken unless flag \a r
 * is given.
 *
 * Special action is taken with symbolic-links; the link itself is removed
 * but the target of the link is left untouched.
 *
 *       FLAGS  | Description
 *       -------|------------
 *              |
 *       r      | Recursive; The delete operation is applied recursively
 *              | if the given argument is a directory. By default, no
 *              | action is taken on a non-empty directory, and an empty
 *              | directory is simply removed.
 *              | 
 *
 * \sa xstr_mkdir(), xfile_rm(), xfile_find()
 *
 * @param[in] pathname The filename/directory to be removed.
 *
 * @return The number of files/directories that were successfully removed is
 * returned. If any errors were encountered the removal process is halted
 * immediately and (size_t)-1 is returned with errno containing the specific
 * errorcode.
 *
 * \a Example:
 * \verbatim
   int main (void)
   {
      if (xfile_mkdir ("newdir1/newdir2/newdir3")) {
         printf ("Directories newdir1/newdir2/newdir3 created\n");
      } else {
         printf ("Unable to create directory newdir\n");
         return EXIT_FAILURE;
      }
      if (xfile_rm ("newdir1", "r")>0) {
         printf ("Removed newdir1\n");
      } else {
         printf ("Could not remove newdir1\n");
      }
      ... 
      return EXIT_SUCCESS;
   }
   \endverbatim
 */ 
size_t xfile_rm (char *pathname, char *flags)
{
#define FL_RECURSIVE    (0x01 << 0)

   size_t ret = 0;
   uint32_t fl = 0;
   xvector_t *flist = NULL;
   char *tflags = flags;

   while (tflags && *tflags) {
      switch (*tflags++) {
         case 'r':   fl |= FL_RECURSIVE;  break;
      }
   }
   xfile_stat_t *file = xfile_stat (pathname);
   if (!file) goto errorexit;

   if (file->type==stat_DIR && (fl & FL_RECURSIVE)) {
      flist = xfile_find (pathname, ".*", "rfdo");
      for (size_t i=0; i<XVECT_LENGTH (flist); i++) {
         xfile_stat_t *f = XVECT_INDEX (flist, i);
         size_t nfiles = xfile_rm (f->name, flags);
         if (nfiles!=(size_t)-1) {
            ret += nfiles;
         }
      }
   }
#ifdef PLATFORM_WINDOWS
   if (file->type!=stat_DIR) {
      if (remove (pathname)!=0) goto errorexit;
   } else {
      if (RemoveDirectory (pathname)==0) goto errorexit;
   }
#else
   if (remove (pathname)!=0) goto errorexit;
#endif
   ret++;

   xvector_iterate (flist, (void (*) (void *))free_fstat);
   xvector_free (flist);
   free (file->name);
   free (file);
   return ret;

errorexit:
   printf ("Removal of '%s' failed, %i: %m\n", pathname, errno);
   if (file) {
      free (file->name);
   }
   free (file);

   xvector_iterate (flist, (void (*) (void *))free_fstat);
   xvector_free (flist);

   return (size_t)-1;
#undef FL_RECURSIVE
}


/**
 * \brief Generates a list of files.
 *
 * Generates a list of files with filenames matching the regex given by
 * \a xregex. Generation is controlled both by the \a xregex as well as
 * the FLAGS. A flag consists of a single ascii character (full list 
 * given below) and can be present in any order in the \a flags parameter.
 *
 * The pathname returned for each of the 'found' [files/directories/other 
 * filetype] is generated by \a xfile_find() during the search of the
 * pathname given. 
 *
 * The return value is a vector of type \a xvector_t containing elements
 * of type \a xfile_stat_t. Each element in the returned vector must be
 * free()ed by the caller. The type \a xfile_stat_t is as follows:
 * \verbatim
enum xfile_type_t {
   stat_REG = 1,
   stat_DIR,
   stat_OTHER,
};
struct xfile_stat_t {
   xfile_type_t type;      // whether regular file, directory or something else
   uint64_t size;          // size of the file in bytes
   size_t link_count;      // number of names this file has (hard links)
   time_t last_access;     // timestamp of last access
   time_t last_modified;   // timestamp of last modification
   char  *name;            // One name of this file; there might be more
};
  \endverbatim
 *
 * Note that the \a name field of the xfile_stat_t structure is allocated
 * using \a free(). The caller must free this field before freeing the 
 * structure.
 *
 * \a xfile_find() understands the following flags:
 *
 *       FLAGS  | Description
 *       -------|------------
 *              |
 *       r      | Recursive; all files and directory of a given directory
 *              | are enumerated in the return value. If any part of your
 *              | expression matches a full filename it will be returned,
 *              | so be very careful with this flag!
 *              | 
 *              | For example, with an expression of ".png", all files in
 *              | a folder called "all.pngs" will be returned even if their
 *              | name does not match ".png". This is because the generated
 *              | name is "all.pngs/filename".
 *              | 
 *       --------------------
 *       f      | Match files in the generated listing. If this flag is
 *              | omitted there will be no results in the returned listing
 *              | that matches files (see xfile_type_t).
 *              | 
 *       --------------------
 *       d      | Match directories in the generated listing. If this flag
 *              | is omitted there will be no results in the returned
 *              | listing that matches directories (see xfile_type_t).
 *              | 
 *       --------------------
 *       o      | Match other filetypes in the generated listing. If this
 *              | flag is omitted there will be no results in the returned
 *              | listing that matches directories (see xfile_type_t) 
 *              | 
 *       --------------------
 *       i      | Ignore case when matching \a xregex. By default matches
 *              | are case-sensitive.
 *              | 
 *       --------------------
 *       e      | Use extended regex when matching xregex. By default
 *              | stand POSIX regex rules are used.
 *              | 
 *
 * \sa xstr_mkdir(), xfile_rm(), xfile_copy()
 *
 * @param[in] pathname  The base pathname to start searching from
 * @param[in] xregex    The regex to use to match each filename against
 * @param[in] flags     Flags (see above) that determine the results
 *
 * @return A list of xfile_stat_t pointers in an xvector_t is returned on 
 * success. Each xfile_stat_t in the xvector_t strcture must be freed be the
 * caller (See \a xfile_stat()). The xvector_t itself must be freed by the
 * caller as well.
 * 
 *
 * \a Example:
 * \verbatim
   int main (void)
   {
      // List all png files in my home directory recursively,
      // excluding those that have digits in the filename and
      // excluding directories. We include "other" for symbolic
      // links.
      xvector_t *results = xfile_find ("/home/me", "[a-zA-Z]+\.png$", "fo");
      for (size_t i=0; i<XVECT_LENGTH (results); i++) {
         xfile_stat_t *file_s = XVECT_INDEX (results, i);
         printf ("Image '%s' is %llu bytes\n", file_s->name, file_s->size);
         free (file_s->name);
         free (file_s);
      }
      xvector_free (results);

      return EXIT_SUCCESS;
   }
   \endverbatim
 */ 

xvector_t *xfile_find (const char *pathname,
                       const char *xregex,
                       const char *flags)
{
#define FL_RECURSIVE       (0x01 << 0)
#define FL_FILE_MATCH      (0x01 << 1)
#define FL_DIR_MATCH       (0x01 << 2)
#define FL_OTHER_MATCH     (0x01 << 3)

   xvector_t *ret             = NULL;
   xfile_stat_t *single_ret   = NULL;

   regex_t preg;
   bool preg_init = false;

   uint32_t fl = 0;
   int rfl = REG_NOSUB; // We don't need match position in the regex

   // Make a note of what flags the caller set
   const char *tmpflags = flags;
   while (tmpflags && *tmpflags) {
      switch (*tmpflags++) {
         case 'r':   fl |= FL_RECURSIVE;     break;
         case 'f':   fl |= FL_FILE_MATCH;    break;
         case 'd':   fl |= FL_DIR_MATCH;     break;
         case 'o':   fl |= FL_OTHER_MATCH;   break;
         case 'i':   rfl |= REG_ICASE;       break;
         case 'e':   rfl |= REG_EXTENDED;    break;
         case 'n':   rfl |= REG_NEWLINE;     break;
      }
   }

   // Compile the regex for later use
   if (regcomp (&preg, xregex, rfl)!=0) goto errorexit;
   preg_init = true;

   // Open the pathname as a directory
   DIR *dentries = opendir (pathname);
   // If it is a directory but some other error occurred, return error
   if (!dentries && errno!=ENOTDIR) {
      goto errorexit;
   }
   // If it isn't a directory, simply return the file fstat in the vector
   if (!dentries && errno==ENOTDIR) {
      // If this pathname doesn't match the regex we simply exit
      if (regexec (&preg, pathname, 0, NULL, 0)!=0) goto errorexit;
      single_ret = xfile_stat (pathname);
      if (!single_ret) goto errorexit;

      xvector_t *tmp = xvector_ins_tail (ret, single_ret);
      if (!tmp) goto errorexit;

      return tmp;
   }

   struct dirent entry, *pentry;

   int rval = safe_readdir (dentries, &entry, &pentry);
   while (rval==0 && pentry!=NULL) {

      bool free_single_ret = true;
      bool matched = false;

      // We cowardly refuse to recurse backwards OR in-place
      if ( (   entry.d_name[0]=='.'
            && entry.d_name[1]=='.' 
            && entry.d_name[2]==0)
         ||
           (   entry.d_name[0]=='.' 
            && entry.d_name[1]==0)) {
         rval = safe_readdir (dentries, &entry, &pentry);
         continue;
      }
      // If this pathname does not match, we ignore it
      matched = regexec (&preg, entry.d_name, 0, NULL, 0)==0 ? true : false;

      // Construct a full pathname
      char *fullpath = xstr_cat (pathname, DIRSEP, entry.d_name, NULL);
      if (!fullpath) goto errorexit;

      // Fstat that pathname
      single_ret = xfile_stat (fullpath);
      free (fullpath);
      if (!single_ret) goto errorexit;

      // If this is a file, and FL_FILE_MATCH is set, we add it
      if ((matched && single_ret->type==stat_REG && (fl & FL_FILE_MATCH))
      // If this is a directory, and FL_DIR_MATCH is set, we add it
      || (matched && single_ret->type==stat_DIR && (fl & FL_DIR_MATCH))
      // If this is 'other' type, and FL_OTHER_MATCH is set, we add it
      || (matched && single_ret->type==stat_OTHER && (fl & FL_OTHER_MATCH))) {
         xvector_t *tmp = xvector_ins_tail (ret, single_ret);
         if (!tmp) goto errorexit;
         ret = tmp;
         free_single_ret = false;
      }

      // If this is a directory and FL_RECURSIVE is set, we recurse
      if (single_ret->type==stat_DIR && (fl & FL_RECURSIVE)) {
         xvector_t *tmp = xfile_find (single_ret->name, xregex, flags);
         xvector_t *new = xvector_join (ret, tmp);

         xvector_free (ret);
         xvector_free (tmp);
         ret = new;
      }

      // Ensure we do not leak memory for those entries we ignored.
      if (free_single_ret) {
         free (single_ret->name);
         free (single_ret);
      }

      // Repeat the loop
      rval = safe_readdir (dentries, &entry, &pentry);
   }

   regfree (&preg);
   closedir (dentries);

   return ret;

errorexit:
   if (preg_init) {
      regfree (&preg);
   }
   if (ret) {
      xvector_iterate (ret, (void (*) (void *))free_fstat);
      xvector_free (ret);
      ret = NULL;
   }
   if (dentries) {
      closedir (dentries);
   }
   if (single_ret) {
      free (single_ret->name);
      free (single_ret);
   }
   return NULL;
#undef FL_RECURSIVE
#undef FL_FILE_MATCH
#undef FL_DIR_MATCH
#undef FL_OTHER_MATCH

}
