@.str.0 = private unnamed_addr constant [17 x i8] c"Greater than 25\0a\00"
@.str.1 = private unnamed_addr constant [26 x i8] c"Less than or equal to 25\0a\00"
; Auto-generated by Nux-LLVM Transpiler (Bare-Metal)
define void @_start() {
  %ret = call i32 @main()
  call i64 asm sideeffect "syscall", "={rax},{rax},{rdi},~{rcx},~{r11},~{memory}"(i64 60, i64 0)
  unreachable
}

define void @print_i64(i64 %n) {
entry:
  %buf = alloca [24 x i8], align 1
  %end = getelementptr [24 x i8], [24 x i8]* %buf, i32 0, i32 23
  store i8 10, i8* %end
  
  %is_neg = icmp slt i64 %n, 0
  %neg_val = sub i64 0, %n
  %val_abs = select i1 %is_neg, i64 %neg_val, i64 %n
  
  br label %loop

loop:
  %curr_val = phi i64 [ %val_abs, %entry ], [ %next_val, %loop_cont ]
  %curr_ptr = phi i8* [ %end, %entry ], [ %next_ptr, %loop_cont ]
  
  %rem = urem i64 %curr_val, 10
  %digit = trunc i64 %rem to i8
  %ascii = add i8 %digit, 48
  
  %next_ptr = getelementptr i8, i8* %curr_ptr, i64 -1
  store i8 %ascii, i8* %next_ptr
  
  %next_val = udiv i64 %curr_val, 10
  %done = icmp eq i64 %next_val, 0
  br i1 %done, label %exit, label %loop_cont

loop_cont:
  br label %loop

exit:
  %final_ptr = phi i8* [ %next_ptr, %loop ]
  
  br i1 %is_neg, label %sign, label %print

sign:
  %sign_ptr = getelementptr i8, i8* %final_ptr, i64 -1
  store i8 45, i8* %sign_ptr
  br label %print

print:
  %p = phi i8* [ %final_ptr, %exit ], [ %sign_ptr, %sign ]
  %p_int = ptrtoint i8* %p to i64
  %end_int = ptrtoint i8* %end to i64
  %len_plus_one = sub i64 %end_int, %p_int
  %len = add i64 %len_plus_one, 1
  
  %res = call i64 asm sideeffect "syscall", "={rax},{rax},{rdi},{rsi},{rdx},~{rcx},~{r11},~{memory}"(i64 1, i64 1, i8* %p, i64 %len)
  ret void
}

define i32 @main() {
  %x.ptr = alloca i64
  store i64 10, i64* %x.ptr
  %y.ptr = alloca i64
  store i64 20, i64* %y.ptr
  %1 = load i64, i64* %x.ptr
  %2 = load i64, i64* %y.ptr
  %3 = add i64 %1, %2
  %z.ptr = alloca i64
  store i64 %3, i64* %z.ptr
  %4 = load i64, i64* %z.ptr
  call void @print_i64(i64 %4)
  %5 = load i64, i64* %z.ptr
  %6 = icmp sgt i64 %5, 25
  %7 = zext i1 %6 to i64
  %8 = icmp ne i64 %7, 0
  br i1 %8, label %then_1, label %else_2
then_1:
  %9 = getelementptr inbounds [17 x i8], [17 x i8]* @.str.0, i32 0, i32 0
  %10 = call i64 asm sideeffect "syscall", "={rax},{rax},{rdi},{rsi},{rdx},~{rcx},~{r11},~{memory}"(i64 1, i64 1, i8* %9, i64 16)
  br label %merge_3
else_2:
  %11 = getelementptr inbounds [26 x i8], [26 x i8]* @.str.1, i32 0, i32 0
  %12 = call i64 asm sideeffect "syscall", "={rax},{rax},{rdi},{rsi},{rdx},~{rcx},~{r11},~{memory}"(i64 1, i64 1, i8* %11, i64 25)
  br label %merge_3
merge_3:
  ret i32 0
}